---
configure_explorer: true
configure_hostname: false
custom_hostname: windows-ansible
configure_start_menu: true
disable_mouse_acceleration: true
remote_desktop_enabled: false
remove_desktop_icons: false
set_sound_scheme: true

install_windows_updates: true
update_categories:
  # You can install only specific updates by uncommenting it
  # * - installs all updates
  - "*"
  # - Critical Updates
  # - Definition Updates
  # - Developer Kits
  # - Feature Packs
  # - Security Updates
  # - Service Packs
  # - Tools
  # - Update Rollups
  # - Updates
  # - Upgrades

change_power_plan: true
# High performance: 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c
# Balanced: 381b4222-f694-41f0-9685-ff5bb260df2e
# Power saver: a1841308-3541-4fab-bc81-f71556f20b4a
power_plan: "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c"

choco_installed_packages:
  # General
  - 7zip
  - adobereader
  - choco-cleaner
  - filezilla
  - kodi
  - mailspring
  - mediainfo
  - mpv
  - qbittorrent
  - rufus
  - vlc
  - vscode
  - windscribe
  # Encoding
  - aegisub
  - handbrake
  - mkvtoolnix
  - gmkvextractgui
  # Driver
  - geforce-game-ready-driver
  # Gaming
  - steam-client
  - discord

# Set cloudflare DNS
dns:
  - adapter: 'Ethernet'
    primary: 1.1.1.1
    secondary: 1.0.0.4

# Set theme to dark mode
configure_theme: true
theme:
  # List of valid values
  # dark
  # aero
  # themeA
  # themeB
  # themeC
  # themeD
  name: "dark"
  app_use_light_theme: 0
  color_prevalence: 0
  enable_transparency: 1
  system_use_light_theme: 0

configure_taskbar: true
taskbar:
  # 00 = Left
  # 01 = Top
  # 02 = Right
  # 03 = Bottom
  position: 03
  # 0 = Left
  # 1 = Middle
  alignment: 0

install_fonts: false
installed_nerdfonts:
  - FiraCode
  - FantasqueSansMono

# List of features: "Get-WindowsOptionalFeature -Online"
install_windows_features: false
windows_features:
  Microsoft-Hyper-V: true

# List of valid distributions that can be installed:
# wsl-alpine
# wsl-archlinux
# wsl-debiangnulinux
# wsl-fedoraremix
# wsl-kalilinux
# wsl-opensuse
# wsl-sles
# wsl-ubuntu-1604
# wsl-ubuntu-1804
# wsl-ubuntu-2004
install_wsl2: false
wsl2_distribution: wsl-ubuntu-2004

remove_bloatware: true
bloatware:
  - Microsoft.BingNews
  - Microsoft.BingWeather
  - Microsoft.GamingApp
  - Microsoft.GetHelp
  - Microsoft.Getstarted
  # - Microsoft.Messaging
  - Microsoft.Microsoft3DViewer
  - Microsoft.MicrosoftOfficeHub
  - Microsoft.MicrosoftSolitaireCollection
  - Microsoft.MicrosoftStickyNotes
  - Microsoft.MixedReality.Portal
  # - Microsoft.MSPaint
  - Microsoft.Office.OneNote
  - Microsoft.OneConnect
  - Microsoft.People
  - Microsoft.PowerAutomateDesktop
  - Microsoft.Print3D
  - Microsoft.ScreenSketch
  - Microsoft.SkypeApp
  - Microsoft.Todos
  # - Microsoft.Windows.Photos
  - Microsoft.WindowsAlarms
  # - Microsoft.WindowsCalculator
  - Microsoft.Wallet
  - Microsoft.WindowsCamera
  # - microsoft.windowscommunicationsapps
  - Microsoft.WindowsFeedbackHub
  - Microsoft.WindowsMaps
  - Microsoft.WindowsSoundRecorder
  - Microsoft.Xbox
  - Microsoft.Xbox.TCUI
  - Microsoft.XboxApp
  - Microsoft.XboxGameOverlay
  - Microsoft.XboxSpeechToTextOverlay
  # - Microsoft.YourPhone
  - Microsoft.ZuneMusic
  - Microsoft.ZuneVideo
  - MicrosoftTeams
